### ISSUE TITLE
ABOUT TIME!

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#1]

**Comment by notoco** [comment]
Będzie poprawione w kolejnej wersji... ;)

**Comment by xxcriticxx** [comment]
jaka ver lite?

zrobie testa dam znac

**Comment by xxcriticxx** [comment]
@notoco podaj jakis film/serial do testow co jest na fili i jest na alltubie

@notoco widze dwie szukajki wytlumaczysz oco biega?

@wisiann zglosie sie do testow

**Comment by xxcriticxx** [comment]
@notoco probowałem million kombinacji nigdy nie znajduje linkow z fili/alltube

**Comment by xxcriticxx** [comment]
@xulek thx za update

**Comment by xxcriticxx** [comment]
@xulek moze po prosimy tutaj @podpis doradzi jak zrobil to z alltube

**Comment by notoco** [comment]
Hehe - miałem wyłączone powiadomienia i nawet nie wiedziałem że tu piszecie...
@xxcriticxx dodałem micro news.txt - specjalnie dla ciebie.

**Comment by wisiann** [comment]
@xxcriticxx,@notoco
Czy mam zassac fanfilm litle z repozytory notoco czy moge robic testy na fan film lite  z cherry team?

**Comment by xxcriticxx** [comment]
@wisiann lite please

**Comment by wisiann** [comment]
Done

**Comment by xxcriticxx** [comment]
@wisiann testuj proxy zobaczy czy masz fili i alltube

**Comment by wisiann** [comment]
Mam wlaczyc recznie proxy w setting i potem zaczac szukac flmow?

**Comment by xxcriticxx** [comment]
@wisiann pierwszo znac dzialajace proxy potem zobacz czy masz linki do alltube i fili

**Comment by notoco** [comment]
@wisian... W notoco zawsze nowsze ff lite niż w cherry. Ja biorę normalny ff od nich, przerabiam, a oni biorą ode mnie...

**Comment by xxcriticxx** [comment]
@notoco gdzie jest ten micro news?

co sie gdzieje zna pigulce? wakajce? malo postow/tutorials

**Comment by wisiann** [comment]
Nie bardzo wiem jak to przetestowac?
Wchodze  w setting-proxy ....wlaczam proxy i naciskam ok 

Co dalej?

**Comment by wisiann** [comment]
@notoco,zniknela opcia wlacz fili.cc,

**Comment by xxcriticxx** [comment]
@wisiann poszukaj jakiegoś serialu i zobacz czy masz linki na fili i tube

**Comment by notoco** [comment]
@wisiann - bo proxy jest ogólne dla obu tych scraperów.

**Comment by wisiann** [comment]
Sprawdzilem kilka polskich seriali,
Belfer,rodzinka .pl watacha ,czas chonoru,
Nie widzialem fili or tube,
50%wogule nie pokazywalo zadnych zrodel,

Na Movie nie mozna wlaczyc wyszukiwania tylko pilskich filmow w Language setting

**Comment by xxcriticxx** [comment]
@wisiann byle jaki seriale bendzie ok nie musz być  pl

**Comment by wisiann** [comment]
Przetestowalem kilka polskich i zagranicznych 
Wyskakuje fili i tube 
Czasami nie ma stream ale to juz inna bajka chyba

**Comment by wisiann** [comment]
Poogladalem dosyc sporo jeden us serial zapodany przez fili ,dobra jakosc ,nie zacina ,mozna miec angielskie i polskie subtitles,  
Takze chyba spoko

**Comment by xxcriticxx** [comment]
@wisiann przez proxy czy vpn?

**Comment by wisiann** [comment]
Proxy

**Comment by xxcriticxx** [comment]
@wisiann gratuluje sukcesu

**Comment by wisiann** [comment]
A u ciebie nie bangla?

**Comment by notoco** [comment]
@wisiann - bangla? Zarzuć jeszcze że coś nie błyka - to się okaże że się znamy...

**Comment by wisiann** [comment]
Ano u mnie błyka az milo ;-)

**Comment by notoco** [comment]
Jeśli znasz błyka i bangla to musisz być uczniem pewnej fizyczki z Opolszczyzny z lat... 90?
