### ISSUE TITLE
pl translations

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#10]
@notoco czy istnieje polskie tlumaczenie wtyczki?

**Comment by notoco** [comment]
Oczywiście. Masz do wyboru język pl i en.

**Comment by xxcriticxx** [comment]
Ale menus mam dalej po engielsku

**Comment by notoco** [comment]
A główny język kodu jaki masz? Sprawdzę potem u siebie jak to działa.

**Comment by xxcriticxx** [comment]
glowny jezyk kodi mam en mam przestawic na pl zeby menus byly po polsku?

![capture](https://user-images.githubusercontent.com/15007183/40776530-00ab009e-6499-11e8-98a2-a7b81faa9530.PNG)

**Comment by xxcriticxx** [comment]
@notoco dobra dziala tesciowa mucho happy!

![capture](https://user-images.githubusercontent.com/15007183/40776679-731bb0ec-6499-11e8-8d60-ba22e043fe20.PNG)

**Comment by notoco** [comment]
Wszak to nasz rodzima wtyczka i musi być PL...

**Comment by xxcriticxx** [comment]
dokladnie 

dla tesciowej wystarczy 

zamykamy

**Comment by notoco** [comment]
Dla teściowej możemy zrobić serbski lub czeski :) i pisany wstecz ;)
