### ISSUE TITLE
Filmweb

### ISSUE THREAD

**Issue by notoco** [notoco/ffl#11]
Taki mały sondaż.
Czy jesteście zainteresowani wykorzystaniem Filmweb w Fanfilm - chodzi o odrębną zakładkę wyświetlającą filmy z top 500 ale także o zakładkę z możliwością wyszukania filmów wg gatunku/kraju i oceny.

**Comment by xxcriticxx** [comment]
nope

**Comment by kopernik1983** [comment]
HAHAHA :P Sondaż extra. Oby jak najwięcej takich heheh :P gdyby cię jeszcze intersewała z jedna opinia to tez jestem za  :P

**Comment by rysson** [comment]
Pomysł wydaje się niezły.
Ale jak się da to osobny moduł (script.*), dzięki czemu da się wykorzystać w innych wtyczkach.

Nie wiem tylko czy to pilne.

**Comment by notoco** [comment]
To nie jest pilne, czasem z tego korzystałem. Jako osobny będzie ciężko, bo korzystamy z bibliotek i funkcji zawartych w fanfilm...

**Comment by xxcriticxx** [comment]
zostalem przeglosowany :(

**Comment by notoco** [comment]
Spokojnie. Liczę się z twoją opinią i na pewno będzie możliwość ukrycia Filmweb co by nie szpeciło ci wyglądu

**Comment by notoco** [comment]
Jak oczyści się wtyczka filmwebboster - to będzie można skorzystać z api które tam jest wykorzystane - filmweb oficjalnie nie ma swojego api - ale jest api dla mobilnych z którego korzystał ramic... nie potrafię tego ugryść...

**Comment by xxcriticxx** [comment]
@notoco to na okladki i opisy filmow?

**Comment by xxcriticxx** [comment]
@notoco check it out

https://github.com/lopezloo/pyfilmweb
https://github.com/ajbrzoz/FWapi
https://bitbucket.org/varabi/filmweb-api

**Comment by notoco** [comment]
thx - już jedno złapałem i męczę.... coś z tego będzie na pewno - może nie od razu ;)
