### ISSUE TITLE
version 1.7

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#13]
@notoco update failed i tak w kolko

**Comment by notoco** [comment]
Wiem. Poprawie wieczorem.

**Comment by xxcriticxx** [comment]
Co nowego w ver 1.7?

**Comment by notoco** [comment]
To tylko update repozytorium, przygotowania do jednej wersji FanFilm - czyli powrót do oryginalnego resolvera, drobne popraweczki w samym repo. W kodzie wtyczki się nic nie zmieniło.
BTW - 1.8 ze względu na problem z updatem 1,7

**Comment by notoco** [comment]
Jak wyjdzie nowa wersja wtyczki - z Filmweb i parowaniem to będzie update repozytorium do 2.0 - i tak już zostanie - sprzątamy - ogarniamy - nadszedł kolejny etap po prostu ;)

**Comment by xxcriticxx** [comment]
aha thx
