### ISSUE TITLE
fili.cc 

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#14]
wprowadzic recaptcha macie to juz w kodzie?

**Comment by xxcriticxx** [comment]
chyba ze ta przyjemnosc tylko na usa

**Comment by notoco** [comment]
chłopie  - my w UE mamy art 13 - nie wiadomo czy cokolwiek będzie....

**Comment by xxcriticxx** [comment]
@notoco w usa trump zakonczyl net neutrality

Neutralność sieci (internetu) – zasada, zgodnie z którą dostawcy usług internetowych (ang. Internet Service Provider) i rządy nie nakładają żadnych ograniczeń na dostęp użytkowników do sieci pozwalających na korzystanie z Internetu

**Comment by notoco** [comment]
Eh - trump jak dla mnie zasługuje na pokojową nagrodę nobla - zakończył konflikt w korei....

**Comment by xxcriticxx** [comment]
@notoco ale off topic zrobiles

**Comment by xulek** [comment]
Spamuje jakby był u siebie :D

**Comment by notoco** [comment]
Ej - ale znacie mnie nie od dziś - mistrz offtopu ;)
