### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#15]
@notoco jest scraper do tego w ff lite?

**Comment by notoco** [comment]
Nie.

**Comment by xulek** [comment]
scraper do portalu społecznościowego? :D

**Comment by xxcriticxx** [comment]
portal społecznościowy to tylko przykrywka są ram filmy/seriale

**Comment by xxcriticxx** [comment]
pytaja nawet o scraper u jsergia
