### ISSUE TITLE
silent scraper

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#16]
pomysl od pana nixgates 

da rade cos takiego wprowadzic w ffl czy czekamy na gotowy kod?

Another cool thing that I thought about the other week is pre-emptive scraping. I've almost got that finished, there's still a bug that I have to iron out though. So what that means is once it gets close to the end of the episode you are watching it will silently scrape and resolve the next episode in the background. This way the next episode plays almost instantly, something I was surprised I hadn't seen yet when I thought of it.

**Comment by kopernik1983** [comment]
Spoko funkcyjka by była :) urzyteczna napewno .

**Comment by rysson** [comment]
U**ż**yteczna na pewno. Od paru tygodni chodzi mi po głowie, ale jeszcze to nie jest ten etap. Możemy poczekać co wymyślą, a jak przez miesiąc czy dwa nie będzie wyników to sami opracujemy to lepiej :-)

**Comment by xxcriticxx** [comment]
New Features:
SmartPlay
Smartplay was one of the major things I wanted to get working with this addon. It is an attempt to provide a Kodi add-on with similar play style to that of a service provider similar to Netflix. Everything is largely streamlined and very user friendly. It provides:

Automatic resuming from TV show selection (select a show and the add-on auto resumes from the last played episode and position of that episode)

provides a different unique and streamlined scraping dialogue. Basic information shown, very user friendly.

Specific episode selection is available through the context menu button "Expand Show" when smartplay is enabled.

Automatic playlist generating, no need to select play from here in the context menu anymore with smartplay enabled. Add-on also auto loads next season into the playlist if the current season finishes playing and the next one is available.

Smartplay also adds the pre-emptive scraping feature. This is now seems to be working without any issues so far. How this works is the add-on identifies that the current video is close to finishing and begins silently scraping the next episode for a show in the background and stores the results for an hour.

Cached scraping and resolved urls.
This allows a user to scrape, play, close a video and then open it again without having to go through the scraping process again. This cached information is only valid for an hour as it's actually a part of pre-emptive scraping but serves as a feature in its own right.

Full trakt sync support
No longer need to have trakt add-on installed if you don't want to. Doesn't break trakt add-on if it is installed.

Torrent Cache support
Torrent types working:

Premiumize

single file torrents

season packs

complete show packs

RD

single file torrents (RD doesn't support streaming from torrents with multiple files.)

Users with both RD and Premiumize services can take advantage of splitting their hosters and torrent files between the services or combining the two servicea. Eg: Premiumize serves torrents and RD serves hoster files or vice versa. This also means you can disable hoster support from premiumize if you are concerned about your data usage with premiumize.

Cache assist (Premiumize only)
If torrents are available, it auto attempts to create a cache copy of a torrent silently in the background on the premiumize servers if there is currently none available. Add-on then notifies you in Kodi if and when it becomes available.

This is currently only available to premiumize users due to the way RD handles their cached torrents. Very unfortunate but I might make it work with single file torrents.

Custom API keys
allows users to supply their own API keys for TMDB, TVDB and Trakt.

Choice between TVDB and TMDB for TV Show information
Allows users to choose whether they want their TV metadata to come from TVDB or TMDB. TMDB is faster and more reliable but can be lacking in some information.

Trakt on Deck (finished)
Trakt on deck coupled with smartplay now works how I wanted it to in Incursion. Shows you the last few shows/movies you watched and then allows you to just select the show and resume from where you were.

Features that were available in Incursion
pre-emptive termination
user can choose to terminate on either only torrents, only hosters or a mixture of the both.

pre-emptive termination can now have a resolution set different to the maximum allowed resolution.

debrid only
Hopefully that covers a lot of it. There will definetely be things that need to be taken care off once I do an Alpha. I've been reluctant to add things to the add-on such as downloading, importing shows/movies to Kodi's library. Things that I feel really hold back users. I would highly suggest that moving forward we as a community try to make use of services like Trakt. But, if there is enough demand I will add them in.

I would like to get some users testing soon so I can get a bunch of shit ironed out (I can already feel my inbox exploding le sigh). I do really only want to look at premiumize users at this point as it has the most features that need to be looked at.

Sort of off topic, I do understand a lot of users are reluctant to use premiumize due to its costs but from everything I've learnt through this process, it really does provide the better service with torrents so, if you want to take the most advantage of torrents, I would highly recommend it. That's not to say I won't be taking care of RD users as well but if you don't mind the extra few dollars a month premiumize really shines through.

I hope this covers a fair bit.

Much love!

**Comment by notoco** [comment]
Ale co to?

**Comment by xxcriticxx** [comment]
@notoco zobaczymy jak @rysson z @xulek skoncza
