### ISSUE TITLE
automatically delete cache

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#17]
auto clear cache on each start of the plugin 

Czy da rade cos takiego zrobic? moze byc opcja on/off pod tools tak jak @tomasiek to kocha!

**Comment by kopernik1983** [comment]
@xxcriticxx to już taki leniwy się zrobiłeś , wiesz ty co  : P

**Comment by xxcriticxx** [comment]
@kopernik1983 taki bajer dla tesciowej/babci i dziadka :)

**Comment by xulek** [comment]
ale cache jest po to żeby zostawał :P dzięki niemu Twoja wtyczka działa szybciej. Kłóci się to trochę z logiką działania ale da się to zrobic :)

**Comment by xxcriticxx** [comment]
ale czasami sie zaswieca i ja trzeba posprzatac
