### ISSUE TITLE
Pomysł na polskie seriale :D

### ISSUE THREAD

**Issue by gzenio22** [notoco/ffl#18]
Tak mi przyszło do głowy mam świadomość ze wtyczki do tych serwisow juz są i funkcjonują ale co wy na to zeby do FF dodac bazy filmow i seriali z ipli i playera? Scrappery juz sa klopotliwe moze byc pewnie dodanie bramki proxy ale ramicowi kiedys takie proxy udalo sie zrobic dla ekstraklasy to czemu w FF nie mialo by sie udac?

Teraz o seriale typu jakies na wspolnej czy pierwsza milosc w takich wtyczkach ciezko a na playerze czy ipli za free jest sporo materiału :D no i wszystkie polskie zony byly by w 7 niebie

**Comment by xxcriticxx** [comment]
@gzenio22 adblock sie znudzil?

**Comment by gzenio22** [comment]
@xxcriticxx Nieee ale po co mam szukac dobrej jakosci materialu przez 10 minut jak moge miec w minute

**Comment by notoco** [comment]
Raczej nikt nie będzie bawił się w iplę i player ze względów prawnych. Za dużo zachodu.

**Comment by gzenio22** [comment]
@notoco W jaki sposob zlamiesz prawo kiedy materiały sa dostepne legalnie i za free? mozna tez dodac mozliwosc logowania do tych serwisow tak jak jest ta opcja dodana do segosa

**Comment by notoco** [comment]
@gzenio22 tu bardziej chodzi o to że prawnicy TVN i Polsatu nie akceptują innych możliwości oglądania ich materiałów... 
@xxcriticxx nie łamię. W PL mogę korzystać.

**Comment by gzenio22** [comment]
zamykam
