### ISSUE TITLE
ekino-tv.pl

### ISSUE THREAD

**Issue by MajkiIT** [notoco/ffl#19]
Hej można dodać tą stronę ?

**Comment by kopernik1983** [comment]
![ashampoo_snap_15 lipca 2018_10h00m14s_001_kodi](https://user-images.githubusercontent.com/33724908/42731844-f31d1214-8815-11e8-87c2-9b95d6f40143.jpg)
![ashampoo_snap_15 lipca 2018_10h04m23s_002_](https://user-images.githubusercontent.com/33724908/42731866-7fec48c2-8816-11e8-9dc0-519b993189e9.jpg)
:)

**Comment by xulek** [comment]
Ale chyba jest jakiś problem bo mimo, że wyszukuje to nie odpala linku. Chyba, że to tylko u mnie :P

**Comment by kopernik1983** [comment]
@xulek  teraz nie sprawdzę bo nie mam jak. plażing  :P

**Comment by xxcriticxx** [comment]
@kopernik1983 plażing, chilling, smażing, grilling, piwing, piszing, spacering?

**Comment by mbebe** [comment]
ekinotv szuka za cloudflare.
tu fix.
[script.module.ptw-1.2.zip](https://github.com/notoco/ffl/files/2244778/script.module.ptw-1.2.zip)

**Comment by notoco** [comment]
@mbebe ... come together right now.... https://github.com/CherryKodi/cherry-dev zapraszamy do współpracy - i sorki że tak późno.

**Comment by xxcriticxx** [comment]
@notoco / @xulek / @mbebe szanowni panie i panowie zamawiam scraper do serwisu serialosy24.pl
