### ISSUE TITLE
nowe serwisy

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#2]
http://serialosy24.pl/
https://virpe.com/ - od meserak86 
https://zalukaj.com/
https://freedisc.pl/
http://www.dailymotion.com - nie wiem jak tam polskie wylapac
https://anyfiles.pl/ - nie wiem jak tam polskie wylapac
https://www.youtube.com - z braku laku
http://filmosy.tv/
http://serialnet.pl/
https://vider.info
https://zaq2.pl

**Comment by notoco** [comment]
Problem jest nie tyle w wyłapaniu co w prawidlowych nazwach filmów zgodnych z tymi z tmdb... Druga rzecz to jakość źródeł. Freedisc czy vider nie oferują nic rewelacyjnego. Reszte na szybko wieczorrm przeglądnę i zobaczymy czy coś tam jest wartego uwagi. Nie ilość a jakość.

**Comment by xxcriticxx** [comment]
@notoco zgadzam sie z jakoscia podalem tyle zebyscie sie nie nudzili z wieczora

**Comment by notoco** [comment]
yt, dailymotion odpada z definicji - tytuły na 100% nie odpowiadają
freedisc, vider, zaq2 - słabizna... nie da się nic dopasować w tytułach - nie ten kontent, przeciętna jakość...
serialosy - no tu by można :)
ALe jak dla mnie - wtyczka ma jż naprawdę dużo serwisów... od unikalnych do przeciętnych...

**Comment by xxcriticxx** [comment]
Ok jeden się znalazła to super

@wisian może coś poda

**Comment by notoco** [comment]
@xxcriticxx - ale to tak na szybko - z pamięci - bo jak chcesz dokładny test.... to zerknij do archiwum wiadomości od ramicspa - robiłem tam testy wszystkiego chyba...

**Comment by xxcriticxx** [comment]
@notoco pamietam twoje reviews

**Comment by wisiann** [comment]
ittv.pl ?

**Comment by notoco** [comment]
To telewizja - tego w ogóle nie ma i nie będzie w FanFilm... to wtyczka filmowa

**Comment by xxcriticxx** [comment]
@wisiann iitvx.pl or iitv.info?

**Comment by notoco** [comment]
iitvx.pl jest w fanfilm...

**Comment by xxcriticxx** [comment]
@notoco wiem ale @wisiann ma chyba wyłączone

**Comment by wisiann** [comment]
To bylo iitv seriale,
Ale nie wiem czy to jeszcze dziala?

**Comment by notoco** [comment]
I jest i działa, ale pod adresem iitvx.pl

**Comment by xxcriticxx** [comment]
iitv.info to jakis clone iitvx.pl

**Comment by notoco** [comment]
No tak to wygląda - a więc niepotrzebny dubel.

**Comment by xxcriticxx** [comment]
@notoco zapytaj na pigulce co ludzie by chcieli dodac

**Comment by notoco** [comment]
Chłopie. Oni by chcieli dodać wszystko, łącznie z grami...

**Comment by xxcriticxx** [comment]
@notoco brygade rr sam sobie wybrales :)

**Comment by notoco** [comment]
Brygadę KWP - wcześniej w brygadzie rmc nie było tak wesoło...

**Comment by xxcriticxx** [comment]
@notoco mowilem tobie zostan na githubie

**Comment by wisiann** [comment]
W jednosci sila !!

**Comment by xxcriticxx** [comment]
@wisiann nie przypalaj wiecej ziola please

**Comment by wisiann** [comment]
Ziola ...to tylko swieze ze swojego ogrodka hehe ;-)

**Comment by gzenio22** [comment]
Jeśli moge pociagne temat ktory zaczynalem u podpisa co do zalukaj moze i na zalukaj jest jakosc 720 P niska ale linki tam nie padaja co chce to znajde i to szybko segos dopiero buduje baze seriali a na zalukaj jest juz tego multum co wazne nie jest to tez po rozwalane nie spotkalem tam zle podpisanego odcinka mam na mysli np najnowszy odcinek jakiegos serialu podpisany pod jakis starszy i na odwrot 

Podpis owszem wyczyscil wtyczke zalukaj ale mi np nie odpala w niej materialow pomimo faktu ze wpisalem dane konta do zalogowania

**Comment by notoco** [comment]
@gzenio22 - pojedyncze źródła i na dodatek vshare - to główna wada zalukaj. Mamy 15 różnych serwisów - to naprawdę dużo jak na tak małą wtyczkę. Teraz chcemy dopracować to co jest.

**Comment by gzenio22** [comment]
@notoco a co jest zlego w Vshare bo nie kumam

**Comment by notoco** [comment]
Strasznie długo się ładuje - i dość często źródełka mają w opisie 720 zaś ich bitrate jest b. niski.... i wychodzą krzaczory. Do serialu spoko - ale do filmów... ciut gorzej. To co masz w zalukaj znajdziesz na alltube,fili czy w szukajce bez problemów.

**Comment by kopernik1983** [comment]
@xxcriticxx  cały czas jestem. obserwuje :P

**Comment by xxcriticxx** [comment]
zrobi mi ktos `serialosy24.pl` czy mam plakac i prosic?

**Comment by gzenio22** [comment]
www.mojseansik.pl

**Comment by xxcriticxx** [comment]
cc @notoco

**Comment by xxcriticxx** [comment]
@gzenio22 

Odtwarzacz niedostępny!
Tylko osoby posiadające konta i konta premium posiadają dostęp do odtwarzaczy w serwisie.
Zarejestruj się już dziś! Rejestracaj jest w pełni darmowa i trwa dosłowie 2 minuty.

**Comment by gzenio22** [comment]
upsi Xd

**Comment by xxcriticxx** [comment]
http://seriale.co/

**Comment by notoco** [comment]
@xxcriticxx wiesz że to nie ode mnie zależy. Gal jest ciut zarobiony teraz. Postaram się ocenić te strony i te najbardziej wartościowe podsunąć.

**Comment by xxcriticxx** [comment]
http://www.efilmy.tv/

**Comment by xxcriticxx** [comment]
@rysson tutaj dalej prowadzimy ten projekt

**Comment by notoco** [comment]
@xxcritixx - skupmy się na serwisach które agregują wiele linków - tak jak np. alltube - to lepsze rozwiązanie niż robienie scrappera do jednej strony z jednym linkiem - dalej stawiamy na jakość niż na ilość

**Comment by xxcriticxx** [comment]
@notoco rozumiem

**Comment by notoco** [comment]
To tak na szybko - dodane "Dziś w TV" - tylko filmy na razie, działa b. ubogo - zczytuje dane z Filmweb ale ze względu na pojawiające się różnice w tytułach i latach pomiędzy FanFilm a trakt,  prowadzi przez wyszukiwarkę do celu...

**Comment by kashkash18** [comment]
To jest to :) o taką opcję walczyłem 😉 Bardzo dobra robota 👍

**Comment by rysson** [comment]
@xxcriticxx, o to ekstra!
A mnie Żona ochrzaniła, że alltube zdechło w MrKnow, to dwa tygodnie temu poprawiłem :-)
I nawet wystawiłem.

Znaczy piszemy własny, czy agregujemy różne?
Pytam, bo źródeł w tym repo nie widzę.

**Comment by rysson** [comment]
Jeszcze z MrKnow rozmawiałem, że trzeba by jego robotę przepisać. Zgodził się i dał zielone światło, ale czasu brakło. Może jakaś ogólna wtyczka, co większość załatwi z pomocą xpath i regex,  resztę µ-wtyczkami?

**Comment by xxcriticxx** [comment]
@rysson hello my friend

**Comment by notoco** [comment]
@rysson źródełka są w zipie. Poprawki zgłaszaj bezpośrednio.  Btw. To jest tylko pomocnicze repo. Główna wtyczką jest FanFilm z repozytorium cherry

**Comment by xxcriticxx** [comment]
@notoco dzieki za update :)

**Comment by notoco** [comment]
@rysson tu masz repo z którego przerabiam fanfilm na fanfilm lite. https://github.com/CherryKodi/CHERRY
Ja praktycznie nie koduję, poprawki drobne naniosłem i kilka rzeczy usprawniłem. Ale za scrappery się nie biorę.

**Comment by xxcriticxx** [comment]
ale @rysson moze za scrappery sie wezmie

**Comment by notoco** [comment]
Zainteresuj się też repo podpis - tam idzie główny front obecnie. Fanfilm jest na chwilę obecną praktycznie kompletny

**Comment by notoco** [comment]
No i tu by było git. Zawsze ręce do pomocy, tylko żebyśmy się nie dublowali a współpracowali. Natomiast luką jest brak filmy online...

**Comment by xxcriticxx** [comment]
@notoco what?

**Comment by xxcriticxx** [comment]
sorry no hablo espanol

zobaczymy z czym @rysson da rade pomoc

**Comment by notoco** [comment]
Do spraw technicznych to i tak nie ja tylko @xulek

**Comment by xxcriticxx** [comment]
@notoco comprende :)

**Comment by rysson** [comment]
@notoco – ok, łapię. Wiem, że da się z zipów pobrac. ~~Ale jak wrzucasz poprawki to lepiej sklonuj CHERRY i tam wrzucaj.~~   Po to git jest :-)
Mój błąd! To też jest tylko binarne. Dobra, pobiorę od Ciebie FanFilm i wrzucę w formie rozpakowanej (albo jak chcesz to sam to możesz). I tam będziemy rzeźbić. Jestem przyzwyczajony do pracy na źródłach nie binarkach. Oczywiście osobne repo z binarkami ma sens bo można od razu podać link w kodi.

Mam ogromne problemy z czasem. Ale co się da to będę łatał.
FanFilm nie używałem. Właściwie to poza goldvod (które mnie zirytowało już dawno) i MrKnow (głównie alltube w nim) to z resztą się nawet za bardzo nie zainteresowałem.

Wybaczcie ignorancję, scrapper 

BTW. Zawsze się zastanawiałem czy lepiej mieć 100 wtyczek czy jedną ze 100 hostami.
Oba rozwiązania mają wady.

BTW2. Widzę, że masz już plan na przyszłość.  Ostatni wpis w new.txt to 2018.**08**.15 :-P

**Comment by rysson** [comment]
Czy ja dobrze widzę, że nie mamy alltube? To może dorzuć na razie to co reaktywowałem (http://kodi.sharkbits.com/filmkodi/) czyli mrknow i skrypty bo od nich zależy.

Swoją droga mogę to wrzucić do githuba, zamiast jakieś stronki robić.

**Comment by xxcriticxx** [comment]
@rysson alltube jest fanfilmie lite ale jest potrzebe polskie ip. Jak nadajesz zagranicy linków z alltube nie zobaaczysz.

**Comment by notoco** [comment]
@rysson obgadam z @xulek temat kodu źródłowego. Cała praca w kodzie jest praktycznie po ich stronie, więc imo to u nich powinien być źródłowy. Co do tego czy lepsza jedna do wszystkiego czy wiele do wszystkich, to fanfilm obejmuje nam filmy które są dobrze opisane. Alltube od podpisa łapie alltube, Phantom łapie CDA. Pozostaje kilka serwisów do których można dopisać odrębne wtyczki (bo w fanfilmie już są). Jak dla mnie fanfilm+Phantom+2-3 wtyczki obejmują cały kontent.
Poza tym - zrekonstruowany został tylko fanfilm. Jakbyś wziął na siebie ożywienie filmy online od mrknow to by było super. Bo tego jednak brakuje.

**Comment by xxcriticxx** [comment]
@notoco link to tego calego cherry please

**Comment by notoco** [comment]
https://github.com/CherryKodi/CHERRY - to repozytorium Polish Team Wizards - twórców buildów (tak wiem....) ale też twórców kilku dodatków do kodi, w tym odpowiedzialnych za odtworzenie FanFilm. Instalacja dodatków nie jest powiązana z instalacją buildu.

**Comment by xxcriticxx** [comment]
@notoco sledze co sie tam dzieje ale tam wiekszosc serwisow tylko z pl (z usa geolock)

**Comment by xxcriticxx** [comment]
@notoco jest filmbooster do testow https://github.com/podpis/kodi/issues/37

**Comment by rysson** [comment]
@notoco, czekaj, czekaj, FanFilm też jest w źródłach MrKnow, pewnie jakiś strasznie stary. 
W repo @xulek na githubie nie widzę FanFilm. Może jest pod inną nazwą, bo tam jest mrowie wtyczek.

Właśnie „filmy online” to wtyczka plugin.video.mrknow, którą zaczałem nieśmiało ozywiać. Fakt, tylko alltube na początek, ale może podniosę resztę.

Co potrzeba najpilniej?

**Comment by xulek** [comment]
U mnie nic nie ma bo ja nie udostępniam fanfilm publicznie. Fanfilm jest dostepny na githubie notoco, cherry i chyba qwer

**Comment by rysson** [comment]
@xulek, dzięki.
 Żeby nam nie zginęło wrzuciłem robotę @notoco fo repo  https://github.com/rysson/fanfilm.lite

Co nam tam potrzeba w pierwszej kolejności?

BTW. @notoco, commitujesz jako root?!  :)

**Comment by notoco** [comment]
@rysson źródła pojawia się tutaj od kolejnej wersji po weekendzie i tu będziemy rzeźbić
Będzie tylko jedna wersja ff bez lite. 
A co złego jest w commit jako root?

**Comment by notoco** [comment]
No chyba że rzeźbimy u ciebie a tu wrzucamy tylko zipy?

**Comment by notoco** [comment]
Co do tego co potrzeba w pierwszej kolejności to ciężko powiedzieć. Fanfilm jest kompletny. Jak się wysypie jakiś scraper to się go poprawia. Grafiki są, nowe opcje są.  
Plugin.video.mrknow był allinone. Ja nie korzystałem, ale wiem że wiele osób lubiło tę koncepcję. Mówisz że działa tam alltube. No to cda, fili, bajki, vod itp.

**Comment by notoco** [comment]
@rysson będę musiał się troszkę podszkolić w githubie żeby to miało ręce i nogi. I nie ukrywam że przydałby mi się jakiś przewodnik.... ja programistą nie jestem - ogarniam tylko jakieś podstawy... Pomożesz?
Widzę że masz w tym większe doświadczenie - w Githubie - więc może źródełka zostawimy u ciebie, a tu tylko będziemy wrzucać gotowe zipy - coby nie robić bałaganu użytkownikom...?

**Comment by rysson** [comment]
@nocto, root może być (z jedną uwagą – patrz niżej) :-) Po prostu koncepcja pracy na z prawami root jest dla mnie obca. Staram się pracować na najniższych uprawnieniach, żeby sobie czegoś nie rozwalić.  :-D

### Git
Mogę trochę wspomóc. Jakimś wymiataczem nie jestem, Python jest moim dodatkowym językiem. Z gitem mam styczność na co dzień, z githubem (czyli git + serwisy) też nie raz.
*Tu właśnie uwaga*. Jak robisz commit, to ustaw sobie wcześniej swoje dane. Nie musisz podawać prywatnych, wystarczy te co są już w GitHubie, np.:
```
git config --global user.name "nocto"
git config --global user.email "36659110+notoco@users.noreply.github.com"
```
### Repo
Co do repo to jak chcesz. To co wczoraj zrobiłem, to jest pomyłka (zmęczenie + piwo). Proponuję `ffl-dev` a czy u Ciebie czy u mnie to drugorzędne. Może rzeczywiście tutaj nie mieszać, to nie będzie głupich pytań, które repo wybrać „ffl” czy ffl-dev”.

Jeśli masz gruntowną rozwałkę (a info o łączeniu lite, znikaniu superfavorites itd to sugeruje) to lepiej poczekam. Jeśli chcesz historię napraw (i wygodnie miejsce aby zajrzeć jak kiedyś było – nie raz im tyłek uratowało), to mogę odtworzyć Twoje zmiany tyle, że w postaci otwartej. Lekko sugeruję z historią, ale nie będę się upierał. Jak wolisz?

### Wtyczki
To może ja się skupię na MrKnow „Filmy Online (czyli plugin.video.mrknow). Żona się ucieszy :)
Jak będzie potrzebne wsparcie gdzieś indziej to pomogę.

### Na koniec
Bardzo się cieszę, że komuś się chce przy tym działać. Jak wiele osób cierpię na chroniczny brak czasu, 
ale tak z doskoku postaram się jak najwięcej zrobić. Jakbyś chciał mail, to jest w moim repo w commitach (jak sobie sklonujesz to znajdziesz). Będzie łatwiej pogadać. Możemy nawet jakiś hangout czasem zestawić.

**Comment by gzenio22** [comment]
http://filmdom.pl

@notoco a co myslisz o tej stronie?

**Comment by xxcriticxx** [comment]
@gzenio22 dawno dodany

**Comment by xxcriticxx** [comment]
https://kraisfilm.pl/

**Comment by gzenio22** [comment]
https://horrortube.pl

**Comment by xxcriticxx** [comment]
@gzenio22 moje codzienne zycie to horror

**Comment by xxcriticxx** [comment]
https://fullvideo.pl/
