### ISSUE TITLE
Orion

### ISSUE THREAD

**Issue by gzenio22** [notoco/ffl#20]
https://koditips.com/orion-kodi-module-indexer/

Co o tym myslicie?

**Comment by notoco** [comment]
B. świeża sprawa, trzba będzie ogarnąć pewnie, ale to nie teraz - teraz trwają porządki.

**Comment by xxcriticxx** [comment]
Pricing for Orion is as follows:

500 daily links for $0.50 per month
2000 daily links for $1.00 per month
5000 daily links for $2.00 per month
20,000 daily links for $3.00 per month
Not since Real Debrid has there been a premium service that can improve Kodi so much for such a little cost.
