### ISSUE TITLE
Pusto pod okladkami

### ISSUE THREAD

**Issue by wisiann** [notoco/ffl#21]
@notoco,czesto pod nowymi filmami nie ma streams, czy to tylko w usa czy okladki filmow sa wrzocane na przod?

**Comment by notoco** [comment]
Nie wiem o co chodzi... jak to nie ma okładek - u mnie są :) Co to znaczy że okładki są wrzucane na przód...

**Comment by wisiann** [comment]
Moze sie zle wyrazilem, 
Jest widoczna okladka nowego filmu np:pitbull,  i pod nia pusto,nie ma zadnych streams,

**Comment by xxcriticxx** [comment]
@wisiann na pewno znalazles faka i zostal usuniety

Pitbull. Ostatni Pies (DVD z książeczką)
Data premiery: 2018-08-23

**Comment by wisiann** [comment]
Sprawdzielm teraz jeszcze raz,
Jest okladka,naciskam wyniki wyszukiwania "0" 
Nie tylko chodzi o ten jedne film ale inne tez,
Nie to zeby sie czepial ale jak nie ma streams to moze okladka powinna byc ukryta do czasu az bedzie mozna ogladac film?

**Comment by wisiann** [comment]
@notoco, 
Pozycja "dzisiaj w tv" jest tylko jedna strona, nie ma opcji "przejdz do nastepnej"

**Comment by wisiann** [comment]
Jakos sie wystrzelilo:-)

**Comment by notoco** [comment]
Żeby stwierdzić że nie ma streamu trzeba by każdy film sprawdzić. Wczytanie samej listy filmów (jest ich chyba po 30 na stronę) trwałoby jakieś 5-6 minut... Każdy film musiałby być sprawdzony w każdym z serwisów...
W dziś tv jest tylko jedna strona, bo tylko tyle jest na stronie która parsujemy. Jest tam 30 filmów. I tylko tyle się wyświetli. Jest owszem możliwość parsowania programu z Filmweb, ale wracamy do punktu wyjścia. Czas działania byłby koszmarny.

**Comment by wisiann** [comment]
@notoco, 
Dzieki za wyjasnienie :)
