### ISSUE TITLE
cda premium only

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#23]

**Comment by notoco** [comment]
Yhm. Jasne. Na kiedy?

**Comment by xxcriticxx** [comment]
@notoco strona się zmieniła na premium only cieszko znałeś darmowy materiał

**Comment by notoco** [comment]
cda.pl ?
Od kiedy? Wczoraj oglądałem... dziś też bez problem znajduje...
https://www.cda.pl/video/show/ca%C5%82e_filmy/p1?duration=dlugie
https://www.cda.pl/Dobre-Kino/vfilm - banglają

**Comment by xxcriticxx** [comment]
No coś tam jest ale nie za wiele

**Comment by kopernik1983** [comment]
Wtyczka Phantom działa normlanie :) rzadko tam zaglądałem na ta stronę więc wizualnie nie potrafię określić czy była tam może jakaś zakładka darmowe czy coś :P Teraz takowej napewno nie ma więc zostaje wyszukiwarka.

**Comment by notoco** [comment]
Nie było nic takiego, mi wynajduje wszystkie filmy które oglądałem w ciągu tygodnia-dwóch.

**Comment by xxcriticxx** [comment]
Tak dokładnie chyba posprzątali i to ostro. Kiedyś była tam zakładka filmy/seriale teraz ja zlikwidowali. Strona wyglonda tak jak by była tylko premium.

**Comment by notoco** [comment]
Nie pamiętam żeby tam była taka zakładka... Zresztą - zawsze korzystałem z wyszukiwajki na ich stronie - i jakoś nie widzę różnicy w wynikach (przynajmniej na filmach które oglądałem w ciągu ostatniego miesiąca - tak daleko już sprawdziłem). Jak dla mnie nie widać różnicy w ilości filmów/seriali - wszystko mi znajduje jak znajdowało...

**Comment by notoco** [comment]
Łap linka z którego korzystam na stronie i w ustwaieniach własnych folderów w phantom:
https://www.cda.pl/video/show/ca%C5%82e_filmy?duration=dlugie&section=&quality=720p&section=&s=date&section=

**Comment by xxcriticxx** [comment]
Thx Tomek

**Comment by notoco** [comment]
As you wish master ..
