### ISSUE TITLE
ver 1.9

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#27]
@notoco caly czas pokazuje ze jest update

**Comment by notoco** [comment]
Zrób aktualizację, ale wcześniej uruchom ponownie kodi. Jakiś czas temu wkradł się błąd, ale już jest ok. Btw. To już koniec tego repozytorium.

**Comment by xxcriticxx** [comment]
@notoco zrób te repo read only

**Comment by xxcriticxx** [comment]
@notoco bedzie potrzebna ver 1.9.1 zeby zrobic ten update

**Comment by notoco** [comment]
@xxcriticxx u mnie zaktualizowało normalnie i nic nie świeci. Sprawdź czy w profilu w addons/temp nie masz staroci jakiś.
Repo będzie zamknięte. Będzie informacja o przejściu na repo cherry. Ale nie dziś

**Comment by notoco** [comment]
Sprawdziłem jeszcze wszystko raz - wszystko jest ok - to jakiś błąd u ciebie.

**Comment by xxcriticxx** [comment]
@notoco zadnego blendu robie update do ver 1.9 i po updatecje dalej pokazuje ze jest update do ver 1.9

**Comment by notoco** [comment]
Poszedł ostatni update do wersji 2.0. Zainstaluj FanFilm z cherry repo.
Nie wiem co robisz - u mnie działa.

**Comment by notoco** [comment]
https://forum.kodiwpigulce.pl/showthread.php?tid=999
