### ISSUE TITLE
Aktualizacja

### ISSUE THREAD

**Issue by kashkash18** [notoco/ffl#4]
Po dzisiejszej aktualizacji , cały zaś świeci mi się by zaktualizować wtyczkę mimo iż wersja jest z 20.05 . Jakie zmiany przy aktualizacji ??

**Comment by notoco** [comment]
No numerki mi się pomieszały w pliku jednym i się zapętliło... Puściłem nową wersję coby zadziałało z automatu.
Zmiany?
https://github.com/notoco/ffl/blob/master/news.txt

**Comment by kashkash18** [comment]
Ok , dzięki za info i poprawki :) zamykam
