### ISSUE TITLE
Brak kilku ikon w zakładce moje seriale

### ISSUE THREAD

**Issue by gzenio22** [notoco/ffl#6]
Brakuje kilku ikonek w zakladce moje seriale 

![screenshot_1](https://user-images.githubusercontent.com/21177361/40544389-63d4292c-6028-11e8-9f9e-a49e0cf93e71.png)

**Comment by notoco** [comment]
Yhm...
Poprawka za 10 minut będzie... oczywiście tylko FF Lite - do dużego FF wyślę info

**Comment by gzenio22** [comment]
wszystko ok? zrobilem cos nie tak?

**Comment by notoco** [comment]
Nie - u ciebie jest ok :)
Możliwe że trzeba będzie zrestartować kodi coby zaciągło nowe ikonki...
