### ISSUE TITLE
ResolveURL v5.0.10 

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/ffl#8]
@notoco wiesz cos na ten temat?

mi zrobil sie update do ver 6.0.7a na reddit.com jsergio napisal 

jsergio123
14 points
·
16 hours ago
There is also an unofficial version being pushed by another repo. Version 6.0.x is not from me.

**Comment by notoco** [comment]
Resolver 6.0.7a jest z repozytorium cherry.
Ma kilka poprawek względem oryginalnego, uwzględniających polskie strony.
Zrób sobie porównanie to zobaczysz że niewiele jest zmienionego.
Zastanawiam się cały czas którego się trzymać w repo. 
FanFilm Lite jest ściśle powiązany z Cherry - i pewne rzeczy mogą lepiej działać w powiązaniu obu.... Jednak co oryginał to oryginał... Ale u mnie i tak się aktualizuje do wersji z repo cherry bo używam kilku wtyczek od nich...
Jak to się mówi - u mnie działa.

**Comment by xxcriticxx** [comment]
thx for info

**Comment by notoco** [comment]
Podejrzewam że jak minie weekend to pojawi się wersja 6.0.10 czyli 5.0.10 z poprawkami uwzględniającymi to, co jest w 6.0.7a...
Wtyczki podpisa świetnie działają z wersją oryginalną, wersja od cherry jest "dopasowana" do kilku wtyczek tam występujących. 
BTW - ramic też miał swój resolver :) uczymy się od najlepszych.

**Comment by xxcriticxx** [comment]
mi ta groupa cherry sie nie podoba

**Comment by kopernik1983** [comment]
@xxcriticxx Nie cieszy mnie ta informacja :) od pewnego czasu sporo sie zmieniło na polskiej scenie kodi :) grupa nie musi ci sie podobac ale mozesz mi wierzyc zrobiła i robi sporo :) oczywiście jak na swoje możliwości które posiada na daną chwilę :) A miałem tylko obserwowac :P ale wywołałeś mnie poniekąd do tablicy :)

**Comment by notoco** [comment]
Ona nie musi ci się podobać. Odwalili kupę roboty, zostały zawarte porozumienia, pakty, zakopane topory (zwał jak zwał). Jednym z efektów tego jest to, że mamy wszyscy dostęp do fanfilm i że mogła powstać wersja ffl. Bez tej grupy nic by nie było.

**Comment by wisiann** [comment]
Co prawda to prawda!
W grupie sila!!😁

**Comment by kopernik1983** [comment]
@wisiann  to prawda :) połaczenie tak naprawdę wszelakich poglądów i wizji na kodi w wersji pl naprawdę nie było ani łatwe ani proste.  @notoco  może potwierdzić. Ale jednak udało sie to zrobić co uważam za bardzo duży sukces. Za tym poszły czyny i mamy to co mamy na dzień dzisiejszy a jest już tego troszke  :)

**Comment by wisiann** [comment]
Wiem ,wiem,git majonez!
Obserwowlem was na KWP ale nie wlaczalem sie do dyskusji bo sa madrzesi odemnie, 😉

**Comment by kopernik1983** [comment]
A resolver namieszał wszystkim :)  no niestety zdażają sie takie sytuacje, nie wszystko da sie dopatrzeć jedno kliknięcie i dziekujemy :) ale jest to względnię szybko wyłapywane więc mozna poprawiać :)

**Comment by notoco** [comment]
@kopernik1983 potwierdzam. Znam to od jednej strony, ale podejrzewam że po drugiej wyglądało to podobnie. Ale się udało.

**Comment by notoco** [comment]
@wisiann na kwp to się pojawiliśmy jak już wszystko było obgadane...

**Comment by wisiann** [comment]
Oby tylko takie  🤔

**Comment by notoco** [comment]
Dzięki temu że działamy razem, KWP, Cherry (a może PTW już), podpis, udaje się to wszystko wspólnie ogarnąć.

**Comment by wisiann** [comment]
Oby tylko takie  🤔

**Comment by wisiann** [comment]
@notoco

To tez git majonez 👊😁

**Comment by kopernik1983** [comment]
majonez musi być :) nie posmarujesz , nie pojedziesz heheh :P

**Comment by wisiann** [comment]
A jak !
Odmeldowuje sie !!

**Comment by xxcriticxx** [comment]
przegapiłem rozmowę ;)

**Comment by wisiann** [comment]
Jeszcze  nie jedno kolko rozancowe sobie to zrobimy haha  😁

**Comment by kopernik1983** [comment]
@xxcriticxx zdarza się :P

**Comment by xxcriticxx** [comment]
amen
