### ISSUE TITLE
Filmwebbooster

### ISSUE THREAD

**Issue by gzenio22** [notoco/ffl#9]
Hej

Nie sądzicie ze dobrze by było to źrudło usunąć z wtyczek? u mnie zawsze odpala sie minutowa jakas reklama na tych linkach i nic wiecej

**Comment by notoco** [comment]
Nie zauważyłem. Jakiś tydzień temu na 100% działało...

**Comment by gzenio22** [comment]
sprawdzisz jak to wyglada teraz? u mnie albo minutowy filmik albo przeskakuje na innne zrodla

**Comment by xxcriticxx** [comment]
@gzenio22 podaj film do testow

**Comment by notoco** [comment]
Nie ma co sprawdzać - cały serwis został mocno przebudowany, łącznie z wtyczką... 
W sumie nie powinien w ogóle nic znajdować - jak znajduje to zczytuje z cache. 
Jakiś tydzień, może dwa temu działało - teraz nie - możesz je sobie wyłączyć w ustawieniach wtyczki, ale podejrzewam że GalAnonim pewnie poprawi w miarę wolnego czasu...

**Comment by gzenio22** [comment]
ja wiem sobie to odznaczylem ale wiesz chodzi o sam fakt nie lepiej ten scraper definitywnie usunac z wtyczki?

**Comment by notoco** [comment]
Jeśli osoba która poprawia scrapery poprawi, to zostanie - ale wydaje mi się że to strata czasu i walka z wiatrakami...

**Comment by xulek** [comment]
u mnie filmwebbooster działa cały czas normalnie i odpala linki

**Comment by notoco** [comment]
No u mnie też nie znajduje niczego... router/konfiguracja ta sama...

**Comment by notoco** [comment]
A teraz ciekawostka - za drugim razem...
![screenshot000](https://user-images.githubusercontent.com/36659110/40745264-48a9234a-6457-11e8-86a5-b9f2cae88b58.png)
Czyli xulek ma racje.... i filmik też odtworzyło...
Nie rozumiem...

**Comment by gzenio22** [comment]
tez miales ten minutowy filmik?

**Comment by notoco** [comment]
Nie. Źródło vshare nie odpowiedziało natomiast streamango poszło aż miło
 Ale fakt faktem że wyszukało za 2 razem.

**Comment by xxcriticxx** [comment]
please podajcie film do tytul filmu do testow

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/40753922-68df91c0-6444-11e8-84d7-df3b3eddaaf2.PNG)

**Comment by notoco** [comment]
@gzenio22 a ty czasem nie lecisz na k18?

**Comment by gzenio22** [comment]
Bo to nadal alfa i widze niedociagniecia nawet w interface np czasem nie lapie ze klikam na dany kafelek

**Comment by xxcriticxx** [comment]
ja testowalem na 17.6 win7

**Comment by timtumturutumtum** [comment]
Kodi18 na mecool m8spro+ działa bez problemu, odpaliło vshare

**Comment by xxcriticxx** [comment]
@gzenio22 zamykamy?

**Comment by gzenio22** [comment]
Taa zobaczymy jak sie sytuacja rozwinie //clossed
